name: Changelog

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 4
    if: "!contains(github.event.head_commit.message, '[nodoc]')"
    steps:
      - uses: actions/checkout@master
      - name: Set up Ruby 3.0.3
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.3
          bundler-cache: true
      - name: Create local changes
        run: |
          gem install github_changelog_generator
          github_changelog_generator -u stimulusreflex -p futurism --token ${{ secrets.GITHUB_TOKEN }} --exclude-labels duplicate,question,invalid,wontfix,nodoc
      - name: Commit files
        run: |
          git config --local user.email "github-actions@example.com"
          git config --local user.name "GitHub Actions"
          git commit -m "[nodoc] update changelog" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
