name: Tests

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - main

jobs:
  ruby_test:
    name: Ruby Test Action
    runs-on: ubuntu-latest
    strategy:
       matrix:
         ruby-version: [2.7.2, '3.0.3']
    steps:
      - uses: actions/checkout@master
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      # - uses: actions/cache@v1
      #   with:
      #     path: vendor/bundle
      #     key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
      #     restore-keys: |
      #       ${{ runner.os }}-gems-
      - name: Install sqlite headers
        run: |
          sudo apt-get update
          sudo apt-get install libsqlite3-dev
      - name: Bundle install
        run: |
          gem install bundler
          gem update --system
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Appraisal
        run: |
          bundle exec appraisal install
      - name: Run ruby tests
        run: |
          gem update --system
          bundle exec appraisal rake test
